### ISSUE TITLE
"Unable to connect to remote server" error in `installs:db-dump` command

### ISSUE THREAD

**Issue by acrobertson** [markbiek/wpe-helper#17]
## The problem

After running `wpeh setup` and entering my API credentials the `installs:find` and `installs:list` commands work as expected, but running `wpeh installs:dump-db` on any of my installs produces this error:

```
In Connection.php line 148:
                                       
  Unable to connect to remote server.  

```

## The ask

Is there any additional configuration required for this to work, or is this a bug?

## My troubleshooting so far

Digging through [the code](https://github.com/markbiek/wpe-helper/blob/master/app/Commands/DumpInstallDatabase.php), I saw that this command also has an `--ssh-key` flag, which defaults to `~/.ssh/id_rsa`. I wasn't clear if this was for the host key or the remote, but since my machine's path is different, I tried running `wpeh installs:dump-db --ssh-key="~/.ssh/wpengine_rsa"` my_install > db.sql.gz`, but that provided the error below, so I suspect that wasn't the issue.

```
In Filesystem.php line 57:
                                                    
  File does not exist at path ~/.ssh/wpengine_rsa.

```

And, as mentioned, the other commands work, so I believe my API key is properly configured.

**Comment by markbiek** [comment]
I'm not sure why, but OSX doesn't like paths that use `~/` when they're passed as cli arguments.

Specifying the full path to the ssh key should work (eg `/Users/alec/.ssh/wpengine_rsa`)
